package sandbox

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Snapshot is a persisted record of a sandbox snapshot exported to S3.
// SessionID may be nil after the underlying sandbox was destroyed
// (FK ON DELETE SET NULL).
type Snapshot struct {
	ID         uuid.UUID      `json:"id"            db:"id"`
	TenantID   uuid.UUID      `json:"tenant_id"     db:"tenant_id"`
	UserID     uuid.UUID      `json:"user_id"       db:"user_id"`
	SessionID  *uuid.UUID     `json:"session_id"    db:"session_id"`
	ObjectKey  string         `json:"object_key"    db:"object_key"`
	SizeBytes  int64          `json:"size_bytes"    db:"size_bytes"`
	ImageRef   string         `json:"image_ref"     db:"image_ref"`
	Metadata   map[string]any `json:"metadata"      db:"metadata"`
	CreatedAt  time.Time      `json:"created_at"    db:"created_at"`
}

// ErrSnapshotNotFound is returned when a snapshot is missing or scoped to
// another tenant (the two are not distinguished, to prevent enumeration).
var ErrSnapshotNotFound = errors.New("snapshot not found")

// SnapshotRepo persists sandbox snapshot metadata. The object payload itself
// lives in MinIO; this repo only stores pointers + sizes + ownership.
type SnapshotRepo struct {
	pool *pgxpool.Pool
}

func NewSnapshotRepo(pool *pgxpool.Pool) *SnapshotRepo {
	return &SnapshotRepo{pool: pool}
}

// Insert writes a new snapshot row. If s.ID is uuid.Nil a new UUID is
// generated by the DB (and not written back to the struct). Metadata may be
// nil and is normalised to {}.
func (r *SnapshotRepo) Insert(ctx context.Context, s *Snapshot) error {
	meta := s.Metadata
	if meta == nil {
		meta = map[string]any{}
	}
	metaJSON, err := json.Marshal(meta)
	if err != nil {
		return fmt.Errorf("marshal metadata: %w", err)
	}
	row := r.pool.QueryRow(ctx, `
INSERT INTO sandbox_snapshots
  (tenant_id, user_id, session_id, object_key, size_bytes, image_ref, metadata)
VALUES ($1,$2,$3,$4,$5,$6,$7)
RETURNING id, created_at`,
		s.TenantID, s.UserID, s.SessionID, s.ObjectKey,
		s.SizeBytes, s.ImageRef, metaJSON)
	if err := row.Scan(&s.ID, &s.CreatedAt); err != nil {
		return fmt.Errorf("insert snapshot: %w", err)
	}
	s.Metadata = meta
	return nil
}

// Get returns a snapshot scoped to tenantID. ErrSnapshotNotFound on miss or
// cross-tenant access.
func (r *SnapshotRepo) Get(ctx context.Context, tenantID, id uuid.UUID) (*Snapshot, error) {
	row := r.pool.QueryRow(ctx, `
SELECT id, tenant_id, user_id, session_id, object_key, size_bytes, image_ref,
       metadata, created_at
FROM sandbox_snapshots
WHERE id=$1 AND tenant_id=$2`, id, tenantID)
	return scanSnapshot(row)
}

// List returns snapshots for tenantID ordered by created_at DESC. If
// sessionID is non-nil, results are restricted to that session. limit must
// be > 0; the caller should pass a sane cap (e.g., 100).
func (r *SnapshotRepo) List(ctx context.Context, tenantID uuid.UUID, sessionID *uuid.UUID, limit int) ([]Snapshot, error) {
	if limit <= 0 {
		limit = 50
	}
	var (
		rows pgx.Rows
		err  error
	)
	if sessionID != nil {
		rows, err = r.pool.Query(ctx, `
SELECT id, tenant_id, user_id, session_id, object_key, size_bytes, image_ref,
       metadata, created_at
FROM sandbox_snapshots
WHERE tenant_id=$1 AND session_id=$2
ORDER BY created_at DESC, id DESC
LIMIT $3`, tenantID, *sessionID, limit)
	} else {
		rows, err = r.pool.Query(ctx, `
SELECT id, tenant_id, user_id, session_id, object_key, size_bytes, image_ref,
       metadata, created_at
FROM sandbox_snapshots
WHERE tenant_id=$1
ORDER BY created_at DESC, id DESC
LIMIT $2`, tenantID, limit)
	}
	if err != nil {
		return nil, fmt.Errorf("query snapshots: %w", err)
	}
	defer rows.Close()

	out := make([]Snapshot, 0)
	for rows.Next() {
		s, err := scanSnapshot(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, *s)
	}
	return out, rows.Err()
}

// Delete removes a snapshot row. Returns ErrSnapshotNotFound if no row
// matched. Not exposed to HTTP in slice 22b; retained for 22b-v2 retention
// tooling.
func (r *SnapshotRepo) Delete(ctx context.Context, tenantID, id uuid.UUID) error {
	tag, err := r.pool.Exec(ctx,
		`DELETE FROM sandbox_snapshots WHERE id=$1 AND tenant_id=$2`,
		id, tenantID)
	if err != nil {
		return fmt.Errorf("delete snapshot: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return ErrSnapshotNotFound
	}
	return nil
}

// scanSnapshot scans a single row from either pool.QueryRow or pgx.Rows
// (both implement Scan with the same signature).
type rowScanner interface {
	Scan(dest ...any) error
}

func scanSnapshot(r rowScanner) (*Snapshot, error) {
	var s Snapshot
	var sessionID *uuid.UUID
	var metaJSON []byte
	if err := r.Scan(&s.ID, &s.TenantID, &s.UserID, &sessionID,
		&s.ObjectKey, &s.SizeBytes, &s.ImageRef, &metaJSON, &s.CreatedAt); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrSnapshotNotFound
		}
		return nil, fmt.Errorf("scan snapshot: %w", err)
	}
	s.SessionID = sessionID
	if len(metaJSON) == 0 {
		s.Metadata = map[string]any{}
	} else if err := json.Unmarshal(metaJSON, &s.Metadata); err != nil {
		return nil, fmt.Errorf("unmarshal metadata: %w", err)
	}
	return &s, nil
}
