{{- if not .Values.secrets.existing -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pca.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pca.serverSelectorLabels" . | nindent 4 }}
type: Opaque
stringData:
  jwt_secret: {{ .Values.secrets.jwtSecret | quote }}
  db_password: {{ .Values.secrets.dbPassword | quote }}
  {{- if .Values.secrets.oidcClientSecret }}
  oidc_client_secret: {{ .Values.secrets.oidcClientSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.snapshotAccessKey }}
  snapshot_access_key: {{ .Values.secrets.snapshotAccessKey | quote }}
  {{- end }}
  {{- if .Values.secrets.snapshotSecretKey }}
  snapshot_secret_key: {{ .Values.secrets.snapshotSecretKey | quote }}
  {{- end }}
{{- end -}}
