{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pca.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pca.serverSelectorLabels" . | nindent 4 }}
{{- end -}}
